apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-api
  labels:
    app: session-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-api
  template:
    metadata:
      labels:
        app: session-api
    spec:
      containers:
      - name: session-api
        image: docker.io/rortegasps/redis-session:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOSTNAME
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
      imagePullSecrets:
      - name: ocilabsecret
---
apiVersion: v1
kind: Service
metadata:
  name: session-api
spec:
  selector:
    app: session-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
